# Generated by Django 4.1.3 on 2022-12-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='info_manage',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
