# Generated by Django 4.1.3 on 2022-12-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_info_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comunidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
