# Generated by Django 4.1.3 on 2022-12-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tiene_reclamacion',
            field=models.BooleanField(default=False),
        ),
    ]
