# Generated by Django 4.1.3 on 2023-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_mtto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('cc', 'Cédula Ciudadanía'), ('ti', 'Tarjeda de Identidad'), ('ce', 'Cédula Extranjería')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
