# Generated by Django 4.1.3 on 2023-01-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_doc_type_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
