# Generated by Django 4.1.3 on 2023-01-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
