# Generated by Django 4.1.5 on 2023-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='donations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
