# Generated by Django 5.0.4 on 2025-08-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_visit_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pareja',
            field=models.ManyToManyField(blank=True, to='users.customuser'),
        ),
    ]
