# Generated by Django 5.0.4 on 2025-08-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_pareja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pareja',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pareja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
