# Generated by Django 5.0.4 on 2025-08-23 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_customuser_pareja_customuser_pareja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pareja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pareja_inversa', to='users.customuser'),
        ),
    ]
