# Generated by Django 4.1.3 on 2022-12-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DianDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('inf_gest', 'Informe de Gestión'), ('cert_antec', 'Certificado de Atecedentes'), ('cert_cump', 'Certificado Cumplimiento Requesitos'), ('pyg', 'Estado de Resultados'), ('balance', 'Estado Situación Financiera'), ('camara', 'Certificado Cámara de Comercio')], max_length=100)),
                ('year', models.IntegerField()),
                ('file', models.FileField(upload_to='dian-docs')),
            ],
        ),
    ]
