# Generated by Django 5.0.4 on 2024-05-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diandoc',
            name='title',
            field=models.CharField(choices=[('Informe de Gestión', 'Informe de Gestión'), ('Certificado de Antecedentes', 'Certificado de Antecedentes'), ('Certificado Cumplimiento Requesitos', 'Certificado Cumplimiento Requesitos'), ('Estado de Resultados', 'Estado de Resultados'), ('Estado Situación Financiera', 'Estado Situación Financiera'), ('Certificado Cámara de Comercio', 'Certificado Cámara de Comercio')], max_length=100),
        ),
    ]
