# Generated by Django 4.1.3 on 2022-12-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dian', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DianDocs',
            new_name='DianDoc',
        ),
    ]
