# Generated by Django 4.1.3 on 2023-01-09 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('costo', models.PositiveIntegerField()),
                ('cancelado', models.BooleanField(default=0)),
                ('imagen', models.ImageField(upload_to='eventos')),
                ('inscritos', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
