# Generated by Django 4.1.3 on 2023-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
