# Generated by Django 4.1.3 on 2023-01-09 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0002_evento_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='costo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
