# Generated by Django 4.1.3 on 2023-01-09 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0003_alter_evento_costo_alter_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Taller', 'Taller'), ('Encuentro', 'Encuentro')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
