# Generated by Django 4.1.3 on 2023-01-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_tipo_alter_evento_inscritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cant_inscritos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='cupos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
