# Generated by Django 4.1.3 on 2023-01-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_inscripciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripciones',
            options={'verbose_name_plural': 'inscripciones'},
        ),
    ]
