# Generated by Django 4.1.3 on 2023-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_inscripciones_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='prueba',
            field=models.BooleanField(default=True),
        ),
    ]
