# Generated by Django 4.1.3 on 2023-01-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_evento_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='costo',
            new_name='costo1',
        ),
        migrations.AddField(
            model_name='evento',
            name='costo2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_costo1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_costo2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
