# Generated by Django 4.1.4 on 2023-01-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0011_evento_costo_evento_fecha_costo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscripciones",
            name="forma_pago",
        ),
    ]
