# Generated by Django 4.1.5 on 2023-01-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_remove_inscripciones_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='duracion',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='incluye',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
