# Generated by Django 5.0.4 on 2024-05-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_inscripciones_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
