# Generated by Django 5.0.4 on 2025-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_alter_evento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='prueba',
            field=models.BooleanField(default=False),
        ),
    ]
