# Generated by Django 4.1.5 on 2023-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_donation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permanencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('formulario', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'permanencia',
            },
        ),
    ]
