# Generated by Django 4.1.3 on 2023-01-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip',
            options={'verbose_name_plural': 'equipos'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
