# Generated by Django 4.1.3 on 2023-01-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0004_alter_equip_options_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equip',
            name='last_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equip',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
