# Generated by Django 4.1.3 on 2023-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0006_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equip',
            name='days_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equip',
            name='days_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equip',
            name='days_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equip',
            name='days_60',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equip',
            name='days_7',
            field=models.BooleanField(default=False),
        ),
    ]
