# Generated by Django 4.1.4 on 2023-04-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mtto", "0007_equip_atrasado_equip_days_14_equip_days_3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equip",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
