# Generated by Django 4.1.4 on 2023-04-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_customuser_donations"),
        ("mtto", "0008_equip_responsable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equip",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customuser",
            ),
        ),
    ]
