# Generated by Django 5.0.4 on 2025-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='tipo',
            field=models.CharField(max_length=80, unique=True, verbose_name='Tipo Documento'),
        ),
    ]
