# Generated by Django 4.1.3 on 2023-01-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_remove_moneymovement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneymovement',
            name='category',
            field=models.CharField(choices=[('venta_huevos', 'Venta huevos'), ('venta_huerta', 'Venta huerta'), ('insumos_gallinas', 'Insumos gallinas'), ('insumos_huerta', 'Insumos huerta'), ('cuido_perros', 'Cuido perros'), ('gasolina', 'Gasolina'), ('cafeteria', 'Insumos cafetería'), ('aseo', 'Insumos aseo'), ('otros_ingresos', 'Otros Ingresos'), ('otros_gastos', 'Otros Gastos')], default='venta_huevos', max_length=20),
        ),
    ]
