# Generated by Django 4.1.3 on 2023-01-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_moneymovement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneymovement',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='total_balance',
            field=models.IntegerField(),
        ),
    ]
