# Generated by Django 4.1.3 on 2023-01-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_mtto'),
        ('visit', '0004_alter_moneymovement_visit_alter_visit_total_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
