# Generated by Django 4.1.3 on 2023-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_alter_visit_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='total_balance',
            field=models.IntegerField(default=0),
        ),
    ]
