# Generated by Django 4.2.4 on 2023-08-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_visitcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneymovement',
            name='fact_elec',
            field=models.BooleanField(default=False),
        ),
    ]
