# Generated by Django 4.2.4 on 2023-08-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0010_moneymovement_fact_elec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneymovement',
            name='fact_elec',
            field=models.BooleanField(default=False, verbose_name='Factura Electrónica'),
        ),
    ]
