# Generated by Django 4.2.4 on 2023-08-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0011_alter_moneymovement_fact_elec'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='facturas_elec',
            field=models.IntegerField(default=0),
        ),
    ]
