# Generated by Django 4.2.4 on 2023-08-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_customuser_visit_resp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50, verbose_name='Proveedor')),
                ('date', models.DateField(verbose_name='Fecha Factura')),
                ('numero', models.CharField(max_length=15, verbose_name='Número Factura')),
                ('valor', models.PositiveBigIntegerField(verbose_name='Valor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'verbose_name_plural': 'facturas',
            },
        ),
    ]
