# Generated by Django 4.1.3 on 2022-12-17 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField(default=datetime.datetime(2022, 12, 17, 15, 50, 54, 706608))),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ed'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('main_media', models.URLField()),
                ('secundary_image', models.ImageField(upload_to='')),
                ('secundary_media', models.URLField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletin.issue')),
            ],
        ),
    ]
