# Generated by Django 4.1.3 on 2022-12-18 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_issue_image_alter_issue_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='main_content',
        ),
        migrations.AddField(
            model_name='article',
            name='sec_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_media',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='secundary_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='secundary_media',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 17, 19, 34, 43, 692568)),
        ),
    ]
