# Generated by Django 4.1.3 on 2022-12-19 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0007_alter_issue_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 21, 20, 0, 934244)),
        ),
    ]
