# Generated by Django 4.1.3 on 2023-01-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0012_alter_issue_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='release_date',
            field=models.DateField(),
        ),
    ]
